5.16/.sti/bin/assemble
5.16/contrib/httpd.conf

Fixing the httpd.conf so apache can serve .pl files. 
@mnagy PTAL

Fix httpd.conf

---

5.16/Dockerfile
5.16/Dockerfile.rhel7

Adding ONBUILD instructions from sti-base

---

hack/build.sh

This reverts commit 9d73672dc3b6204f89d7488cfa2086b8bd453834.

Revert "squash on build"

---

5.16/.sti/bin/usage
README.md

Updated docs and usage with new flag naming in STI

---

5.16/.sti/bin/assemble
5.16/.sti/bin/run
5.16/contrib/src/.bashrc
Makefile
hack/build.sh

For details, see: https://github.com/openshift/sti-base/pull/35

Remove bashrc sourcing in STI scripts

---

README.md

Rewording parts of the README.md file

---

5.16/s2i/bin/run
5.20/s2i/bin/run
README.md

Add support for Hot Deploy

---

5.16/s2i/bin/assemble
5.20/s2i/bin/assemble

Fix directory permissions after assemble is complete

---

5.20/Dockerfile.rhel7

Related: openshift/postgresql/pull/75

Sync Red Hat build service labels

---

5.20/s2i/bin/usage

Fix image name in s2i usage message

---

5.20/README.md
5.20/s2i/bin/assemble
5.20/test/psgi-variables/application1.psgi
5.20/test/psgi-variables/application2.psgi
5.20/test/psgi-variables/cpanfile
5.20/test/psgi/application.psgi
5.20/test/psgi/cpanfile
5.20/test/run

This resolves [https://github.com/openshift/sti-perl/issues/58]. It requires the augmented test/run from [https://github.com/openshift/sti-perl/pull/60] pull request.

Add PSGI support

---

5.16/README.md
5.16/s2i/bin/usage
5.20/README.md
5.20/s2i/bin/usage
README.md

Replace sti with s2i

---

5.16/README.md
5.16/contrib/etc/httpd.d/50-mpm.conf.template
5.16/s2i/bin/run
5.20/README.md
5.20/contrib/etc/httpd.d/50-mpm.conf.template
5.20/s2i/bin/run

For trello card https://trello.com/c/HbqjUI5y/881-3-update-perl-image-to-autoconfigure-based-on-available-memory

Add server limit logic

---

5.20/s2i/bin/assemble

@ppisar PTAL. This is a cosmetic change, but I had real troubles reading and parsing the line in my head, I am hoping this is much simpler now. I found this while trying to hunt a test failure which I'll fix in an additional update to this PR, but I want to make it fail first so I can see the difference.
[test]

Make PSGI_FILE test more readable

---

5.24/Dockerfile.rhel7

To use subscription inside container yum command has to be run first (before yum-config-manager)

Fix using subscription in container

---

5.24/Dockerfile

Enable testing repository for rh-perl524, since it is not yet released

---

5.16/Dockerfile.rhel7
5.20/Dockerfile.rhel7
5.24/Dockerfile.rhel7

Labels now should follow spec at https://github.com/projectatomic/ContainerApplicationGenericLabels/blob/master/vendor/redhat/labels.md

New labels for OSBS

---

5.16/test/run
5.20/test/run
5.24/test/run

This may lead to conflicts with tests for different repository.
@hhorak @bparees Please take a look.

Do not publish a container's port(s) to the host in tests

---

5.20/test/run
5.24/test/run

Similarily to: sclorg/s2i-python-container#229

tests: replace removed s2i flag

---

5.20/Dockerfile
5.20/Dockerfile.rhel7
5.24/Dockerfile
5.24/Dockerfile.rhel7
README.md

Few edits in top-level README
Remove hard-coded /opt/app-root in Dockerfile
Remove release label, because it is bumped automatically

Various small documentation related changes

---

examples/templates/sample-test-app.json

https://github.com/openshift/origin/pull/17922#pullrequestreview-86819501

Replace 'template.openshift.io' with 'openshift.io'

---

5.20/root/opt/app-root/etc/scl_enable
5.24/root/opt/app-root/etc/scl_enable

This will allow us to update to newer nodejs smoothly.

Use a variable for NodeJS SCL name

---

5.20/test/run
5.24/test/run

Just checks whether npm is available and is able to install some package.

Add test for npm availability

---

5.24/README.md

Document npm purpose and no guarantee for version

---

imagestreams/perl-rhel7-ppc64le.json

rename imagestream from perl_ppc64le to perl

rename imagestream from perl_ppc64le to perl

---

5.24/test/run

Test npm availability also for 5.26

---

imagestreams/perl-centos7.json
imagestreams/perl-rhel7-ppc64le.json
imagestreams/perl-rhel7.json

This pull request removes a minor typo for all the image stream descriptions.

Removing Version Typo from Image Stream Descriptions

---

imagestreams/perl-centos7.json
imagestreams/perl-rhel7.json

This pull request updates the CentOS and RHEL descriptions for the perl image streams to the perl 5.26 README.

Updating CentOS and RHEL to 5.26 README for Latest Image Stream Description

---

5.24/README.md
5.26-mod_fcgid/README.md
5.26/README.md

Corect the directory name: .sti -> .s2i

Fix documentation for environment variables

---

imagestreams/perl-centos7.json
imagestreams/perl-rhel7.json

per request from @siamaksade from OpenShift PM, this PR removes EOF version from the imagestream file
@hhorak @bparees

remove versions that are EOL

---

imagestreams/perl-rhel7-s390x.json

Similar PR to sclorg/mariadb-container#115

Add imagestream file for s390x

---

5.26-mod_fcgid/test/run
5.26/test/run
5.30/test/run
imagestreams/perl-centos7.json
imagestreams/perl-ubi8.json
test/check_imagestreams.py

This commit adds a test for checking the latest version in imagestreams.

Test the latest versions in the imagestreams

---

5.26-mod_fcgid/test/run
5.26/test/run
5.30/test/run

Function check_result now returns return code so the test suite can catch failures.

Fix check_result function

---

imagestreams/perl-centos.json

Use Quay.io in imagestreams

---

5.26/Dockerfile
5.26/Dockerfile.rhel7
5.26/README.md
5.26/s2i/bin/run
5.30/Dockerfile
5.30/Dockerfile.fedora
5.30/Dockerfile.rhel7
5.30/README.md
5.30/s2i/bin/run
examples/from-dockerfile/5.26/Dockerfile
examples/from-dockerfile/5.30/Dockerfile
test/run

enable scl env variable, based on that is not necessary to use versioned from-dockerfiles examples

enable scl variables

---

.github/workflows/centos7-openshift-tests.yaml
.github/workflows/centos7-tests.yaml
.github/workflows/fedora-tests.yaml

Add proper plan for Fedora and CentOS7 workflow

---

5.26-mod_fcgid/README.md
5.26/README.md
5.30-mod_fcgid/README.md
5.30/README.md

There were information about nodejs, probably copy/paste from other
repository.

Fix README files

---

.github/workflows/build-and-push.yml

Add Build and Push GitHub Action to Quay.io

---

5.26/README.md
5.30/README.md
examples/from-dockerfile/5.26/Dockerfile
examples/from-dockerfile/5.30/Dockerfile

There are some issues:
* multiple use of CMD not allowed
* sed -i '1i...' don't work, you need to describe -e before command
* sed on non-exiting file isn't possible

Fix example of build in documentation and code

---

.github/workflows/build-and-push.yml

version and include are not called properly. Let's use only include

Fix calling GitHub matrix

---

5.26/Dockerfile
5.26/Dockerfile.rhel7
5.30/Dockerfile.rhel7

`PKGG_CONFIG_PATH` is probably a typo.
If not feel free to discard this PR.

change PKGG_CONFIG_PATH to PKG_CONFIG_PATH

---

.github/workflows/build-and-push.yml

and rebuild image every wednesday

use composite build-and-push github action

---

.github/workflows/docker-tests.yml

Use Fedora-latest compose for Fedora tests

---

test/run

**Warning: this requires https://github.com/sclorg/container-common-scripts/pull/238 to be merged first.**
Avoids unnecessary code duplication

Use a function from test-lib.sh for checking result and other actions

---

.github/workflows/container-tests.yml
.github/workflows/openshift-tests.yml

Update compose for RHEL8-8.6.0 nightly.

Update Testing Farm for using RHEL8-8.6.0

---

.github/workflows/build-and-push.yml
5.32/Dockerfile.fedora

This pull request adds support for Fedora Perl-5.32 container image.

Support perl 5.32 and Fedora

---

5.26-mod_fcgid/test/test-openshift.yaml
5.26/test/test-openshift.yaml
5.30-mod_fcgid/test/test-openshift.yaml
5.30/test/test-openshift.yaml
5.32/test/test-openshift.yaml
5.34/test/test-openshift.yaml

Do not use double symlinks

---

.github/workflows/build-and-push.yml

update build-and-push action to v4

---

examples/templates/sample-test-app.json
test/run-openshift
test/run-openshift-remote-cluster
test/test-lib-perl.sh

This pull request adds test called `test_latest_imagestreams` also for OpenShift 4 case.

Test latest_imagestreams to OpenShift 4 as well.

---

test/run-modfcgid

Add check if the new value is present in application and increase timeout for sure.

Add check if new value is really present

---

5.32/Dockerfile.rhel8

Add Dockerfile.rhel8 for version 5.32
Support start since May 2022.
This pull request adds support for building and testing version 5.32 in RHEL8
Closes: #306

Add Dockerfile.rhel8 for version 5.32

---

.github/workflows/container-tests.yml
.github/workflows/openshift-tests.yml
5.26-mod_fcgid/README.md
5.26/README.md
5.30/README.md
5.32/README.md
5.34/README.md
5.36/README.md
5.38/README.md
README.md
examples/README.md
imagestreams/imagestreams.yaml
imagestreams/perl-centos.json
imagestreams/perl-rhel.json
test/run
test/run-modfcgid

This pull request removes RHEL-7 building and testing from this repository.

Remove RHEL-7 support - EOL June 2024

---

imagestreams/imagestreams.yaml
imagestreams/perl-rhel.json
test/test_dancer_ex_standalone.py
test/test_dancer_ex_templates.py
test/test_deploy_templates.py
test/test_imagestreams_quickstart.py
test/test_latest_imagestreams.py

Use VERSION instead of SINGLE_VERSION like we do in whole org

---

5.30-mod_fcgid/test/test_helm_dancer_app.py
5.30-mod_fcgid/test/test_helm_dancer_mysql_template.py
5.30-mod_fcgid/test/test_helm_perl_imagestreams.py
5.30/test/test_helm_dancer_app.py
5.30/test/test_helm_dancer_mysql_template.py
5.30/test/test_helm_perl_imagestreams.py
5.32/test/test_helm_dancer_app.py
5.32/test/test_helm_dancer_mysql_template.py
5.32/test/test_helm_perl_imagestreams.py
5.34/test/test_helm_dancer_app.py
5.34/test/test_helm_dancer_mysql_template.py
5.34/test/test_helm_perl_imagestreams.py
5.36/test/test_helm_dancer_app.py
5.36/test/test_helm_dancer_mysql_template.py
5.36/test/test_helm_perl_imagestreams.py
5.38/test/test_helm_dancer_app.py
5.38/test/test_helm_dancer_mysql_template.py
5.38/test/test_helm_perl_imagestreams.py
5.40/test/test_helm_dancer_app.py
5.40/test/test_helm_dancer_mysql_template.py
5.40/test/test_helm_perl_imagestreams.py
test/test_helm_dancer_app.py
test/test_helm_dancer_mysql_template.py
test/test_helm_perl_imagestreams.py

This pull request adds support possibilty to test helm charts directly in perl-container.
helm charts are tested against https://github.com/sclorg/helm-chart repo.

Add support testig helm charts in Perl container

---

.github/workflows/build-and-push.yml

Support building and pushing Perl 5.40 to quay.io registry

---

.github/auto-merge.yml
.github/workflows/auto-merge-on-demand.yml
.github/workflows/auto-merge.yml
.github/workflows/pr-metadata.yml

Allow checking CI and Reviews for automerging

---

.github/workflows/build-and-push.yml
5.40/Dockerfile.fedora

Remove duplicate raws in build-and-push.yml

---

.github/workflows/build-and-push.yml

Update build-and-push to use ubuntu-20.04

---

.github/workflows/openshift-pytests.yml
.github/workflows/openshift-tests.yml

Support testing perl-5.40 verion on OpenShift as well.

---

.github/workflows/build-and-push.yml
.github/workflows/container-tests.yml

The current version has been retired
https://ubuntu.com/about/release-cycle

Switch ubuntu-20.04 to ubuntu-latest.
