- 5.16/Dockerfile.rhel7
- 5.20/Dockerfile.rhel7
It is recommended not to use MAINTAINER in RHEL images.
> Remove MAINTAINER in RHEL image

- 5.20/Dockerfile
- 5.20/Dockerfile.rhel7
This removes unnecessary PATH modification. It's not needed because adding a collection path is properly handled by scl_enable script in perl 5.20 Dockerfile. The code was unintentionally  preserved while porting from 5.16.
> Remove unnecessary PATH modification

- hack/build.sh
RHSL-2.0-based images will have different namespace than the old "openshift". See mongodb commit:
commit 63f60041b941b6f9c942e32a03dd8c5c02fa4a0f
Author: Ben Parees <bparees@redhat.com>
Date:   Fri Sep 18 13:20:13 2015 -0400
support multiple namespaces for pushing
> support multiple namespaces for pushing

- Makefile
- hack/build.sh
- hack/common.mk
- hack/ directory should be _just_ mirrored
- Makefile should be as declarative as possible
- build.sh should not rely on repository name
> sync build-scripts with other images

- 5.16/contrib/etc/httpdconf.sed
- 5.20/contrib/etc/httpdconf.sed
Copy the behavior of php images: https://github.com/openshift/sti-php/pull/64
PTAL @mfojtik @rhcarvalho
BTW, should we add the same Logs section as we have for PHP? Right now we don't have such section but IMHO it may be useful.
> Configure Apache to write access logs to stdout instead of file.

- 5.16/README.md
- 5.20/README.md
- README.md
This is similar to https://github.com/openshift/mysql/pull/99. It allows us to maintain two separate variant for every version (default values, image names, links to doc and eventually more, that may be or already is different). As a bonus, we'll have a clean `README.md` with only image-related usage information that can be used in Docker Hub or elsewhere.
> Split README.md to usage and general part

- 5.20/s2i/bin/run
- 5.20/test/binpath/cpanfile
- 5.20/test/binpath/index.pl
- 5.20/test/run
It's not possible to execute scripts coming from CPAN. This is because the ~/extlib/bin is not in the PATH. Also ~/extlib/lib/perl5 must be added to Perl's include through environment variable in order to such script executed via kernel's execve() know where CPAN Perl modules  are installed.
This also augments the test/run script so that new tests can be added later.
> Fix executing script installed from CPAN

- 5.16/contrib/etc/httpdconf.sed
- 5.20/contrib/etc/httpdconf.sed
- 5.20/test/run
- 5.20/test/warningonstderr/index.pl
This patch set fixes issue #72.
> Log httpd log_error to stderr

- 5.16/test/run
- 5.20/test/run
This patch set fixes misspellings in test comments and a bug in a test.
> Correct typos in tests

- 5.16/contrib/etc/httpdconf.sed
- 5.20/contrib/etc/httpdconf.sed
- 5.20/test/run
This addresses issue #75 by log errors to standard output instead of storing them into a file. That was the main concern of the original issue #72.
It also preserves tests to make sure the errors are logged to standard output and to provide the useful test framework features.
Once support for docker 1.8 is dropped, reverting this tiny change will provide logging to error output.
> Log errors to stdout

- 5.16/contrib/etc/httpdconf.sed
- 5.20/contrib/etc/httpdconf.sed
- 5.20/test/run
Docker 1.8.2 cannot open /proc/self/fd files. The only way how to
write to standard output is to write to already opened descriptor.
In order to obtain httpd errors from docker client, we send error to
standard output too.
I've checked it with 1.8.2 and 1.9.1 this time.
<https://github.com/openshift/sti-perl/pull/78>
> Log to stdout via cat

- 5.16/contrib/etc/httpd.d/50-mpm.conf.template
- 5.20/contrib/etc/httpd.d/50-mpm.conf.template
Since we're processing our custom configuration before reading system
config files, the MPM prefork module is not loaded at the time of the
evaluation. Since this image will always run with Prefork (threaded
workers don't work with Perl), we can always set the settings, not
needing to check for the module to be loaded.
Fixes RHBZ https://bugzilla.redhat.com/show_bug.cgi?id=1339514
@bparees PTAL
> Remove IfModule check

- 5.16/s2i/bin/assemble
- 5.20/s2i/bin/assemble
Currently, users need to add '--mirror' option along with mirror URL
in CPAN_MIRROR env var in order to work correctly. However, that option
'--mirror' shouldn't be a part of CPAN_MIRROR as it's rather confusing
to add an option into an env var that is used for mirror URL only.
Signed-off-by: Vu Dinh <vdinh@redhat.com>
> Separate --mirror argument from CPAN_MIRROR env var

- 5.16/s2i/bin/assemble
- 5.20/s2i/bin/assemble
Curl and cpanm ignore HTTP_PROXY and only use http_proxy. Set http_proxy
to HTTP_PROXY in case only the later is set.
Output error if curl fails.
> Handle uppercase HTTP_PROXY

- 5.16/cccp.yml
- 5.20/cccp.yml
This is for the purpose of building these containers on
CentOS Container Pipeline.
> Added cccp.yml for building on the centos container pipeline.

- 5.20/test/run
- 5.24/Dockerfile
- 5.24/Dockerfile.rhel7
- 5.24/README.md
- 5.24/cccp.yml
- 5.24/contrib/etc/httpd.conf
- 5.24/contrib/etc/httpd.d/50-mpm.conf.template
- 5.24/contrib/etc/httpdconf.sed
- 5.24/contrib/etc/scl_enable
- 5.24/s2i/bin/assemble
- 5.24/s2i/bin/run
- 5.24/s2i/bin/usage
- 5.24/test/binpath/cpanfile
- 5.24/test/binpath/index.pl
- 5.24/test/psgi-variables/application1.psgi
- 5.24/test/psgi-variables/application2.psgi
- 5.24/test/psgi-variables/cpanfile
- 5.24/test/psgi/application.psgi
- 5.24/test/psgi/cpanfile
- 5.24/test/run
- 5.24/test/sample-test-app/cpanfile
- 5.24/test/sample-test-app/index.pl
- 5.24/test/warningonstderr/index.pl
- Makefile
- README.md
This patchset adds support for rh-perl524 collection. It adds support for source-to-image-1.0.3 as discussed on https://github.com/sclorg/s2i-perl-container/pull/99 to work on Fedora 23. Then it adds support for rh-perl524 collection and finally it disables the collection in the top-level Makefile because CentOS is still missing the rh-perl524 packages (not to break automated CentOS tests). The last commit will be reverted once the collection appears in the CentOS.
> rh-perl524 support

- 5.16/Dockerfile.rhel7
- 5.20/Dockerfile.rhel7
Enabling host repositories didn't work with docker 1.10 and newer inside OpenStack. It was fixed in latest rhel7 base release, so using 'rhel7' base image is required for RHEL CI. Postgresql PR - sclorg/postgresql-container#150
Also to enable repositories inside container running 'yum' first is required - see https://access.redhat.com/solutions/1443553 . Similar to sclorg/s2i-base-container#99 .
@hhorak @bparees Please take a look and merge.
> Fix using subscription in container

- 5.20/Dockerfile
- 5.24/Dockerfile
For centos/ namespaced images use centos/ namespaced s2i base image. This image is based on https://github.com/sclorg/s2i-base-container/ and is built by coreservices-jenkins maintained by RHSCL team.
@hhorak @bparees Please take a look and merge.
> Use centos/ namespaced s2i base image

- 5.20/root/opt/app-root/etc/scl_enable
- 5.24/root/opt/app-root/etc/scl_enable
Similarly to https://github.com/sclorg/s2i-python-container/pull/209
> Enable rh-nodejs6, so users can use npm for installing JavaScript stuff

- imagestreams/perl-rhel7-ppc64le.json
Adding rhel7 based perl 5.26 imagestream that will support ppc64le.
> imagestream definition for rhel based perl 5.26 on ppc64le

- 5.24/test/run-openshift
- 5.26/test/run-openshift
It is necessary to define `NAME` variable, so we don't need to guess names of the services.
> Update common submodule and fix tests

- 5.20/test/run-openshift
- 5.24/test/run-openshift
- 5.26/test/run-openshift
- README.md
- imagestreams/perl-centos7.json
- imagestreams/perl-rhel7-ppc64le.json
- imagestreams/perl-rhel7.json
docs.openshift.org to docs.okd.io
github.com/openshift/dancer-ex to github.com/sclorg/dancer-ex
> OKD rebranding and sclorg move

- 5.26/Dockerfile.fedora
- 5.26/root/opt/app-root/etc/httpdconf-fed.sed
Add Fedora based image - based on content of fedora dist-git + applied changes made in CentOS Dockerfile.
Fedora uses by default 'event' MPM module, so switch to 'prefork'
to provide same user experience as with RHEL7 image.
> Add Fedora based image

- 5.26-mod_fcgid/Dockerfile.rhel8
- 5.26-mod_fcgid/README.md
- 5.26-mod_fcgid/content_sets.yml
- 5.26-mod_fcgid/help.md
- 5.26-mod_fcgid/root/opt/app-root/Plack-1.0047-Work-around-mod_fcgid-bogus-SCRIPT_NAME-PATH_INFO.patch
- 5.26-mod_fcgid/root/opt/app-root/etc/httpd.conf
- 5.26-mod_fcgid/root/opt/app-root/etc/httpd.d/50-mpm.conf.template
- 5.26-mod_fcgid/root/opt/app-root/etc/httpdconf.sed
- 5.26-mod_fcgid/root/opt/app-root/psgiwrapper
- 5.26-mod_fcgid/s2i/bin/assemble
- 5.26-mod_fcgid/s2i/bin/run
- 5.26-mod_fcgid/s2i/bin/usage
- 5.26-mod_fcgid/test/binpath/cpanfile
- 5.26-mod_fcgid/test/binpath/index.pl
- 5.26-mod_fcgid/test/fcgi/another.fcgi
- 5.26-mod_fcgid/test/fcgi/index.fcgi
- 5.26-mod_fcgid/test/psgi-variables/application1.psgi
- 5.26-mod_fcgid/test/psgi-variables/application2.psgi
- 5.26-mod_fcgid/test/psgi-variables/cpanfile
- 5.26-mod_fcgid/test/psgi/application.psgi
- 5.26-mod_fcgid/test/psgi/cpanfile
- 5.26-mod_fcgid/test/run
- 5.26-mod_fcgid/test/run-openshift
- 5.26-mod_fcgid/test/sample-test-app
- 5.26-mod_fcgid/test/sample-test-app.json
- 5.26-mod_fcgid/test/test-lib-openshift.sh
- 5.26-mod_fcgid/test/test-lib.sh
- 5.26-mod_fcgid/test/warningonstderr/index.pl
- Makefile
- README.md
5.26-mod_fcgid differs from 5.26. 5.26 was built on Perl 5.26 and
mod_perl from RHSCL. 5.26-mod_fcgid is built on Perl 5.26 and
mod_fcgid from modules.
RHEL7 does not contain perl-FCGI. 5.26-mod_fcgid removed SCL
infrastructure. Thus 5.26-mod_fcgi is not supported on RHEL7.
F29 does not contain non-modular 5.26 and perl-FCGI for 5.26. F28
contains Perl 5.26, but mod_fcgid is broken there. Thus 5.26-mod_fcgi
is not supported on Fedora.
> Add Perl 5.26 with mod_fcgid for RHEL-8 Beta

- 5.24/Dockerfile
- 5.24/Dockerfile.rhel7
Some core modules do not live on CPAN and cannot be installed in an
assemble phase. E.g. Devel::Peek.
This patch preinstalls rh-perl524-perl-core RPM package that ensures
that all core modules are available in the assemble phase.
This is not an issue for 5.26 where the same guarantee is implemented
by explicitly installed rh-perl526-perl RPM package.
> 5.24: Install all core modules

- 5.24/s2i/bin/assemble
- 5.26-mod_fcgid/s2i/bin/assemble
- 5.26/s2i/bin/assemble
Adds fix-permissions right after `mv` command. `cp` command also has parameter `-a`.
Reference issue:
https://github.com/sclorg/container-common-scripts/issues/119
> Fix permissions for all files given in s2i

- 5.24/s2i/bin/assemble
- 5.24/test/run
- 5.26/s2i/bin/assemble
- 5.26/test/run
Add parameter `ct_build_s2i_npm_variables`
into `run_s2i_build` function.
It checks if internal NPM_REGISTRY is set and
CA file is present. Else use public NPM registry.
> Add support for internal Nexus registry

- 5.26-mod_fcgid/s2i/bin/assemble
- 5.26-mod_fcgid/test/run
- 5.26/test/run
Fix npm_test and update container-common-scripts.
Update container-common-scripts to the latest.
This patch builds an image before testing
npm functionality. It is a prerequisite for the npm test
to have a built image.
> Fix npm_test and update container-common-scripts

- Makefile
In order to test the latest versions in
OpenShift environment, we need the latest
version at the end of variable VERSIONS.
This is done in all sclorg organization.
> The latest version at the end of VERSIONS

- 5.26-mod_fcgid/test/run
- 5.26/test/run
- 5.30/test/run
Run all tests and reports failures at the end.
The commit executes all tests and reports
at the end result in format like:
[PASSED] test_sample_test_app
[PASSED] test_binpath
[PASSED] test_psgi
[PASSED] test_psgi_variables
[PASSED] test_warningonstderr
[PASSED] test_npm
Tests for rhscl/perl-526-rhel7 succeeded.
> Run all tests and reports failures at the end

- 5.16/README.md
- 5.20/README.md
- 5.26-mod_fcgid/README.md
- 5.26/README.md
- 5.30/README.md
This correct types introduced in commit ad12949496e45c1a6f8fb9a48e0279ddf75c9299.
> Fix typos an formatting in READMEs

- 5.26-mod_fcgid/README.md
The examples introduced in commit
ad12949496e45c1a6f8fb9a48e0279ddf75c9299 presume mod_perl, but they do
not work with mod_fcgid.
This patch reworks the example to properly configure FCGI server from
a PSGI application where needed, i.e. in 5.26-mod_fcgid.
> Fix "own setup" example for mod_fcgid images

- 5.26/Dockerfile
- 5.26/README.md
- 5.30/Dockerfile
- 5.30/README.md
- README.md
This commit adds support for Quay.io registry instead of Docker.io registry.
Docker.io registry adds rate limits which sometimes blocks our test suite.
> Use quay io instead docker

- imagestreams/perl-centos.json
- imagestreams/perl-rhel.json
> Deprecate perl-5.26 imagestreams for RHEL7 and CentOS7

- 5.26-mod_fcgid/test/test-lib-remote-openshift.sh
- 5.26/test/test-lib-remote-openshift.sh
- 5.30/test/test-lib-remote-openshift.sh
- test/run-openshift-remote-cluster
- test/test-lib-perl.sh
- test/test-lib-remote-openshift.sh
This pull request brings a testing s2i-perl-container inside OpenShift 4 environment.
To execute tests inside the OpenShift 4 environment just write as a PR comment `test-openshift-4`.
> Support testing s2i-perl-container in OpenShift 4

- 5.26-mod_fcgid/README.md
- 5.30-mod_fcgid/README.md
This variable doesn't exist in FCGI version.
> Remove obsolete information about PERL_APACHE2_RELOAD variable

- imagestreams/perl-centos.json
- imagestreams/perl-rhel-aarch64.json
- imagestreams/perl-rhel.json
Non-groupified objects were deprecated in OCP 4.7.
> Use groupified apiVersion

- test/run
If second test in test_from_dockerfile() fails, test pass still before
this change.
> Fix test_from_dockerfile() exit code check

- test/run
- test/run-modfcgid
When calling readline do not use the -z option.
From the readline manpage
-z, --zero
end each output line with NUL, not newline
This fixes the following two bash warnings
test/run: line 11: warning: command substitution: ignored null byte in
input
test/run: line 12: warning: command substitution: ignored null byte in
input
> Fix two bash warnings

- 5.26-mod_fcgid/README.md
- 5.26-mod_fcgid/s2i/bin/assemble
- 5.26-mod_fcgid/s2i/bin/run
- 5.26-mod_fcgid/test/psgi-hot_deploy
- 5.30-mod_fcgid/README.md
- 5.30-mod_fcgid/s2i/bin/assemble
- 5.30-mod_fcgid/s2i/bin/run
- 5.30-mod_fcgid/test/psgi-hot_deploy
- 5.32/README.md
- 5.32/s2i/bin/assemble
- 5.32/s2i/bin/run
- 5.32/test/psgi-hot_deploy
- test/psgi-hot_deploy/cpanfile
- test/psgi-hot_deploy/index.psgi
- test/psgi-hot_deploy/lib/My/Test.pm
- test/run-modfcgid
Again rebase of https://github.com/sclorg/s2i-perl-container/pull/221
> Support PSGI reload

- test/run-openshift-remote-cluster
Nowadays, we use the external OpenShift registry for the testing image.
OpenShift 4 provides an internal OpenShift registry. Let's use it.
> Use Internal OpenShift 4 registry instead of external

- test/run-modfcgid
The `ct_run_tests_from_testset` is already used in `test/run` file.
This PR proposes to use it also in `test/run-modfcgid`
> Use generic run tests

- 5.26-mod_fcgid/test/test-openshift.yaml
- 5.26/test/test-openshift.yaml
- 5.30-mod_fcgid/test/test-openshift.yaml
- 5.30/test/test-openshift.yaml
- 5.32/test/test-openshift.yaml
- 5.34/test/test-openshift.yaml
- test/run-openshift-remote-cluster
- test/test-lib-perl.sh
- test/test-openshift.yaml
This pull request adds support for testing perl-container in CVP pipeline.
The changes are this one:
* `common` directory updated to the latest
* `test/test-openshift.yaml` is the symlink from `common`
* Each version has as well symlink from `test/test-openshift.yaml`
* support testing imagestream in `test-lib-perl.sh`
* tagging image for CVP pipeline in `run-openshift-remote-cluster`
> Support for CVP pipeline

- 5.26-mod_fcgid/Dockerfile.rhel8
- 5.26/Dockerfile.fedora
- 5.30-mod_fcgid/Dockerfile.rhel8
- 5.30/Dockerfile.fedora
- 5.32/Dockerfile.c9s
- 5.32/Dockerfile.fedora
- 5.32/Dockerfile.rhel9
- 5.34/Dockerfile.c9s
- 5.34/Dockerfile.fedora
Otherwise when a wrong stream is installed, it's only found by scl test, which is too late in the process and might even go through uncought, especially when the scl test is removed for non-SCL distros at some point.
> Add a test in Dockerfile directly to check the version

- test/run-modfcgid
We already use `ct_init` in `test/run`. This PR adds `ct_init` also to `test/run-modfcgid`.
+ use generic function for 'wait for pid' and 'check result'.
> use ct_init for modfcgid

- test/run
- test/run-modfcgid
This is not running on OpenShift
> Fix description of test

- examples/templates/sample-test-app.json
- test/test-lib-perl.sh
This PR migrates DeploymentConfig to Deployment.
See more info here:
https://docs.openshift.com/container-platform/4.12/applications/deployments/what-deployments-are.html
Since OPenShift 4.14 DeploymentConfigs are deprecated: https://access.redhat.com/articles/7041372
> This PR migrates DeploymentConfig to Deployment

- imagestreams/perl-centos.json
- imagestreams/perl-rhel-aarch64.json
- imagestreams/perl-rhel.json
Perl 5.30 went EOL in November 2023: https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle
@yselkowitz FYI if you don't mind looking at the changes
> Remove 5.30 imagestreams

- .github/workflows/openshift-tests.yml
- imagestreams/imagestreams.yaml
- imagestreams/perl-centos.json
- imagestreams/perl-rhel-aarch64.json
- imagestreams/perl-rhel.json
Add support for checking imagestreams before running tests on OpenSHift 4
> Add imagestream generator

- .github/workflows/openshift-pytests.yml
The GitHub action is similar like here:
https://github.com/sclorg/httpd-container/blob/master/.github/workflows/openshift-pytests.yml or https://github.com/sclorg/mariadb-container/blob/master/.github/workflows/openshift-pytests.yml
And the tests are triggered properly.
> Add GitHub Action for execution PyTest in OpenShift 4

- .github/workflows/container-tests.yml
- .github/workflows/openshift-pytests.yml
- .github/workflows/openshift-tests.yml
This pull request only enables testing perl container on RHEL10 host
No code is changed only GitHub Action itself
> Support enabling perl-container on RHEL10

- test/test_dancer_ex_standalone.py
- test/test_dancer_ex_templates.py
- test/test_helm_dancer_app.py
- test/test_helm_dancer_mysql_template.py
- test/test_helm_perl_imagestreams.py
> Helm charts were renamed to 'redhat-' prefix

- test/run-openshift-remote-cluster
- test/test-lib-perl.sh
- test/test_dancer_ex_standalone.py
- test/test_dancer_ex_templates.py
- test/test_deploy_templates.py
- test/test_helm_dancer_app.py
- test/test_helm_dancer_mysql_template.py
- test/test_helm_perl_imagestreams.py
- test/test_imagestreams_quickstart.py
This pull request fixes OpenShift tests.
The tests are now performed on Shared Cluster
> Fixing OpenShift Pytest test suite

- 5.32/README.md
- README.md
- imagestreams/imagestreams.yaml
- imagestreams/perl-centos.json
- imagestreams/perl-rhel-aarch64.json
- imagestreams/perl-rhel.json
- test/test_helm_dancer_mysql_template.py
- test/test_helm_perl_imagestreams.py
- test/test_imagestreams_quickstart.py
and update the README.md to reflect this change and suggest rhel9 instead
> Deprecate version 5.32 for rhel8
